name: Telegram API
     on:
       push:
         branches:
           - main
     jobs:
       api:
         runs-on: ubuntu-latest
         steps:
           - uses: actions/checkout@v3
           - name: Set up Node.js
             uses: actions/setup-node@v3
             with:
               node-version: '16'
           - name: Install dependencies
             run: npm install express axios
           - name: Run API server
             run: |
               echo "Starting API server with secrets..."
               node -e 'require("express")().post("/api/telegram", async (req, res) => { const axios = require("axios"); try { await axios.post(`https://api.telegram.org/bot${process.env.TELEGRAM_TOKEN}/sendMessage`, { chat_id: process.env.CHAT_ID, text: req.body.message }); res.json({ success: true }); } catch (error) { res.status(500).json({ error: error.message }); } }).listen(3000)'
             env:
               TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
               CHAT_ID: ${{ secrets.CHAT_ID }}
